# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8081}
    error.whitelabel.enabled: false
# PROFILES
spring:
    application.name: discovery-service
    profiles.active: prod
# EUREKA
#  instance:
#      hostname: localhost
#      port: ${port:8081}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
# LOGGING
logging.level.org.springframework.security: DEBUG
